import os
import httpx
import streamlit as st

BACKEND_URL = os.getenv("BACKEND_URL", "http://fastapi-app:8000")

st.set_page_config(
    page_title="docpilot",
    page_icon="📄",
    layout="wide",
)

st.title("📄 docpilot")
st.caption("Ask questions about your documents · every answer includes citations")

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Upload document")

    uploaded = st.file_uploader(
        "Drop a PDF, TXT, MD, or DOCX",
        type=["pdf", "txt", "md", "docx"],
    )

    if uploaded and st.button("Ingest", type="primary"):
        with st.spinner(f"Ingesting {uploaded.name}…"):
            try:
                resp = httpx.post(
                    f"{BACKEND_URL}/api/ingest",
                    files={
                        "file": (uploaded.name, uploaded.getvalue(), uploaded.type)
                    },
                    timeout=120.0,
                )
                resp.raise_for_status()
                data = resp.json()
                st.success(
                    f"✅ {data['chunks_stored']} chunks stored "
                    f"from **{data['source_file']}**"
                )
            except Exception as e:
                st.error(f"Ingestion failed: {e}")

    st.divider()
    st.header("Settings")

    top_k = st.slider(
        "Chunks to retrieve (top-k)",
        min_value=1, max_value=10, value=5,
        help="Higher = more context but slower. Start at 5.",
    )

    st.divider()
    st.header("Collection stats")

    if st.button("Refresh"):
        try:
            r = httpx.get(f"{BACKEND_URL}/api/stats", timeout=10.0)
            s = r.json()
            st.metric("Total chunks", s["total_chunks"])
            st.caption(f"Embedding: {s['embedding_model']}")
            st.caption(f"Chunk size: {s['chunk_size']} tokens")
            st.caption(f"Overlap: {s['chunk_overlap']} tokens")
        except Exception as e:
            st.error(str(e))

# ── Chat state ────────────────────────────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": (
                "👋 Upload a document in the sidebar then ask me anything.\n\n"
                "Every answer shows the exact source chunks used — "
                "you can always verify where the answer came from."
            ),
            "sources": [],
        }
    ]


def render_sources(sources: list):
    """Render citation expander below an answer."""
    if not sources:
        return
    with st.expander(f"📎 {len(sources)} source(s) — click to verify", expanded=False):
        for i, src in enumerate(sources, 1):
            page = f" · page {src['page_number']}" if src.get("page_number") else ""
            score_color = "green" if src["score"] > 0.7 else "orange" if src["score"] > 0.5 else "red"
            st.markdown(
                f"**[{i}] {src['source_file']}{page}** — "
                f":{score_color}[score: {src['score']}]"
            )
            st.caption(src["text"])
            if i < len(sources):
                st.divider()


# ── Render chat history ───────────────────────────────────────────────────────
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        render_sources(msg.get("sources", []))

# ── Handle new input ──────────────────────────────────────────────────────────
if prompt := st.chat_input("Ask a question about your documents…"):

    st.session_state.messages.append(
        {"role": "user", "content": prompt, "sources": []}
    )
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving and generating…"):
            try:
                resp = httpx.post(
                    f"{BACKEND_URL}/api/query",
                    json={"question": prompt, "top_k": top_k},
                    timeout=120.0,
                )
                resp.raise_for_status()
                data = resp.json()
                answer = data["answer"]
                sources = data.get("sources", [])
                model = data.get("model", "unknown")
            except httpx.ConnectError:
                answer = "⚠️ Cannot reach the backend. Is docpilot running?"
                sources = []
                model = ""
            except Exception as e:
                answer = f"⚠️ Error: {e}"
                sources = []
                model = ""

        st.markdown(answer)
        if model:
            st.caption(f"Generated by {model}")
        render_sources(sources)

    st.session_state.messages.append(
        {"role": "assistant", "content": answer, "sources": sources}
    )