version: "3.9"

networks:
  docpilot-net:
    driver: bridge

volumes:
  qdrant-data:
  ollama-data:

services:
    qdrant:
      image: docker.io/qdrant/qdrant:latest
      container_name: qdrant
      ports:
        - "6333:6333"
        - "6334:6334"
      volumes:
        - qdrant-data:/qdrant/storage
      networks:
        - docpilot-net
      restart: unless-stopped

    ollama:
      image: docker.io/ollama/ollama:latest
      container_name: ollama
      ports:
        - "11434:11434"
      volumes:
        - ollama-data:/root/.ollama
      networks:
        - docpilot-net
      restart: unless-stopped

    fastapi-app:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: fastapi-app
      env_file: .env
      ports:
        - "8000:8000"
      volumes:
        - ./docs:/app/docs
      networks:
        - docpilot-net
      depends_on:
        - qdrant
        - ollama
      restart: unless-stopped